# Generated by Django 2.0.3 on 2018-04-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='DateOfAdmission',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='DateOfDischarge',
            field=models.DateField(),
        ),
    ]
